### ISSUE TITLE
Odd errors on uco-core:target and uco-core:hasFacet properties

### ISSUE THREAD

**Issue by fabrizio-turchi** [ucoProject/UCO-Utility-Pre-0.7.0-Validator#5]
I don't know how to fix the following issues raised by the tool:
[example_UFED_CHAT_WHATSAPP.zip](https://github.com/ucoProject/UCO-Utility-Pre-0.7.0-Validator/files/6284463/example_UFED_CHAT_WHATSAPP.zip)

- Constraint Error: Line 276, Class <uco-observable:ObservableRelationship> Property <uco-core:target
> Property has 6 values but must have at most 1.
- Constraint Error: Line 664, Class <uco-observable:ObservableObject> Property <uco-core:hasFacet> Property's value  is a <None> but must be a <uco-core:Facet>.
- Constraint Error: Line 730, Class <uco-observable:ObservableObject> Property <uco-core:hasFacet> Property's value  is a <None> but must be a <uco-core:Facet>.
- Constraint Error: Line 796, Class <uco-observable:ObservableObject> Property <uco-core:hasFacet> Property's value  is a <None> but must be a <uco-core:Facet>.

**Comment by stanbernsteen** [comment]
The data contains sixobjects with the same @id kb:12e73810-d005-45d5-8314-815867799faa.  When the data gets converted to triples, all six objects with the same @id are treated as a single object.  Each of the six objects has a uco-core:target, so the tool sees six uco-core:targets assigned to the same single object.

This may have confused the tool and caused the other errors, too.
